// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportManager.Data;

#nullable disable

namespace SportManager.Migrations
{
    [DbContext(typeof(SportContext))]
    [Migration("20260330092137_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SportManager.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("SportManager.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Endurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstBlesse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Force")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PosteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Technique")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitesse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("PosteId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("SportManager.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Equipe1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Equipe2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Equipe1Id");

                    b.HasIndex("Equipe2Id");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("SportManager.Models.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnduranceMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForceMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TechniqueMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitesseMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Postes");
                });

            modelBuilder.Entity("SportManager.Models.Joueur", b =>
                {
                    b.HasOne("SportManager.Models.Equipe", "Equipe")
                        .WithMany("Joueurs")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportManager.Models.Poste", "Poste")
                        .WithMany()
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("SportManager.Models.Match", b =>
                {
                    b.HasOne("SportManager.Models.Equipe", "Equipe1")
                        .WithMany()
                        .HasForeignKey("Equipe1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportManager.Models.Equipe", "Equipe2")
                        .WithMany()
                        .HasForeignKey("Equipe2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe1");

                    b.Navigation("Equipe2");
                });

            modelBuilder.Entity("SportManager.Models.Equipe", b =>
                {
                    b.Navigation("Joueurs");
                });
#pragma warning restore 612, 618
        }
    }
}
